### PR TITLE
Show error on bad stop delete

### LINKED ISSUE #344: Delete Stop Button does not work. Seems like no API is called
To access this page, go to a route > edit trip > add/edit stop/ > choose a stop

We are unable to delete incorrect stop now.

image

### PR DESCRIPTION
**Pull request by LoneRifle**
* stores/modals - implement `showErrorModal` which delegates to `showModal`
* refactor codebase to use `showErrorModal` where suitable

Fixes #344

### CODE REVIEW

File: beeline-admin/components/routes/CrowdstartDisplay.vue [hunk 1]
```diff
@@ -139,13 +139,7 @@ export default {
...
         }
       })
-      .catch((err) => this.showModal({
-        component: 'CommonModals',
-        props: {
-          type: 'alert',
-          message: _.get(err, 'message')
-        }
-      }))
+      .catch(this.showErrorModal)
```
Comment (xkjyeah) [inline beeline-admin/components/routes/CrowdstartDisplay.vue]: uh... i'm not sure whether this works, or whether you need to write `err => this.showErrorModal`. It's because the callback to a Promise is executed, the context is null.

Comment (LoneRifle) [reply beeline-admin/components/routes/CrowdstartDisplay.vue]: screen shot 2017-11-20 at 5 22 02 pm
